"""W-Agent 框架包"""

__version__ = "2.0.0a1"
__author__ = "LuckyStar2456"
__license__ = "MIT"

# 导出核心模块
from w_agent.core.agent import BaseAgent
from w_agent.container.bean_factory import BeanFactory, BeanDefinition, Scope
from w_agent.config.dynamic_config import DynamicConfigManager
from w_agent.core.decorators import (
    AgentComponent,
    ServiceComponent,
    ToolComponent,
    RepositoryComponent,
    ControllerComponent,
    Component,
    PostConstruct,
    PreDestroy,
    Autowired,
    Qualifier,
    Retry,
    CircuitBreaker,
)
from w_agent.core.event_bus import EventBus, Event, ConfigChangedEvent
from w_agent.core.doctor import Doctor
from w_agent.lifecycle.manager import LifecycleManager
from w_agent.lifecycle.order import LifecycleOrder
from w_agent.aop.pointcut import (
    AspectJPointcut,
    BeforeAdvice,
    AfterAdvice,
    AroundAdvice,
)
from w_agent.aop.proxy_factory import ProxyFactory
from w_agent.aop.joinpoint import JoinPoint
from w_agent.aop.aspects import RetryAspect, CircuitBreakerAspect
from w_agent.observability.tracing import global_tracer
from w_agent.observability.health import (
    CompositeHealthIndicator,
    HealthIndicator,
    LLMHealthIndicator,
)
from w_agent.distributed.lock import RedisDistributedLock
from w_agent.distributed.lock_pool import LockRenewalPool
from w_agent.resilience.bulkhead import ResilienceManager
from w_agent.skills.sandbox.wasm_sandbox import WasmSkillSandbox
from w_agent.skills.sandbox.nsjail_sandbox import NsJailSkillSandbox
from w_agent.skills.skill import Skill
from w_agent.exceptions.framework_errors import (
    BeanNotFoundError,
    CircularDependencyError,
    InjectionError,
    SkillSandboxError,
)
from w_agent.scanner.parallel_scanner import ParallelASTScanner
from w_agent.lifecycle.graceful_shutdown import GracefulShutdownManager
from w_agent.tools.langchain_adapter import LangChainToolAdapter
from w_agent.kernel import (
    AmbiguousCapabilityError,
    CapabilityDeclaration,
    CapabilityNotFoundError,
    CapabilityRequirement,
    Contribution,
    EffectScope,
    EventDispatcher,
    EventStop,
    FunctionPlugin,
    KernelError,
    Plugin,
    PluginContext,
    PluginDependencyError,
    PluginError,
    PluginHandle,
    PluginLoadError,
    PluginManager,
    PluginRecord,
    PluginReference,
    PluginSpec,
    PluginState,
    PluginUnloadError,
    Registration,
    RegistrationError,
    Registry,
    RegistryView,
    ScopePath,
    ScopeSegment,
    discover_entrypoint_plugins,
    import_plugin,
    load_yaml_references,
    plugin,
)
from w_agent.models import (
    MODEL_PROVIDER_CAPABILITY,
    AnthropicMessagesMapping,
    AttemptOutcome,
    AttemptRecord,
    AudioContent,
    BUILTIN_PROVIDER_TEMPLATES,
    BlockEnd,
    BlockStart,
    CancellationToken,
    CandidateEvaluation,
    CandidateMetrics,
    CandidateState,
    EndpointProbe,
    ErrorEvent,
    FinishEvent,
    FinishReason,
    HealthStatus,
    HttpModelProfile,
    HttpModelProvider,
    HttpProviderMapping,
    HttpProviderTransport,
    HttpRequest,
    HttpStreamDecoder,
    HttpStreamFormat,
    HttpStreamFrame,
    HttpxOpenAICompatibleTransport,
    HttpxProviderTransport,
    ImageContent,
    InvocationPolicy,
    InvocationPolicyProtocol,
    MessageRole,
    ModelCapability,
    ModelDescriptor,
    ModelError,
    ModelExecutor,
    ModelFailure,
    ModelFailureKind,
    ModelMessage,
    ModelInvocationError,
    ModelInvocationResult,
    ModelProvider,
    ModelProviderProbe,
    ModelRegistry,
    ModelRequest,
    ModelResponse,
    ModelRouter,
    ModelStreamProtocolError,
    GeminiGenerateContentMapping,
    OllamaChatMapping,
    OpenAICompatibleModelProfile,
    OpenAICompatibleProvider,
    OpenAICompatibleTransport,
    PeriodicProbeService,
    ProbeCache,
    ProbeCheck,
    ProbeLevel,
    ProbeMode,
    ProbeResult,
    ProbeStatus,
    ProviderTemplate,
    ProviderTemplateRegistry,
    QwenDashScopeMapping,
    RouteCandidate,
    RouteDecision,
    RouteRequest,
    RoutingError,
    RoutingPolicy,
    RoutingWeights,
    TextContent,
    TextDelta,
    TokenUsage,
    ToolCallContent,
    ToolCallDelta,
    ToolDefinition,
    ToolResultContent,
    UsageEvent,
    WeightedRoutingPolicy,
    YamlRoutingPolicy,
    anthropic_provider,
    builtin_provider_template_registry,
    collect_stream,
    deepseek_provider,
    gemini_provider,
    glm_provider,
    ollama_provider,
    qwen_compatible_provider,
    qwen_native_provider,
    turbo_provider,
)

__all__ = [
    "BaseAgent",
    "BeanFactory",
    "BeanDefinition",
    "Scope",
    "DynamicConfigManager",
    "AgentComponent",
    "ServiceComponent",
    "ToolComponent",
    "RepositoryComponent",
    "ControllerComponent",
    "Component",
    "PostConstruct",
    "PreDestroy",
    "Autowired",
    "Qualifier",
    "Retry",
    "CircuitBreaker",
    "EventBus",
    "Event",
    "ConfigChangedEvent",
    "Doctor",
    "LifecycleManager",
    "LifecycleOrder",
    "GracefulShutdownManager",
    "ResilienceManager",
    "AspectJPointcut",
    "BeforeAdvice",
    "AfterAdvice",
    "AroundAdvice",
    "ProxyFactory",
    "JoinPoint",
    "RetryAspect",
    "CircuitBreakerAspect",
    "global_tracer",
    "CompositeHealthIndicator",
    "HealthIndicator",
    "LLMHealthIndicator",
    "RedisDistributedLock",
    "LockRenewalPool",
    "WasmSkillSandbox",
    "NsJailSkillSandbox",
    "Skill",
    "BeanNotFoundError",
    "CircularDependencyError",
    "InjectionError",
    "SkillSandboxError",
    "ParallelASTScanner",
    "LangChainToolAdapter",
    "AmbiguousCapabilityError",
    "CapabilityDeclaration",
    "CapabilityNotFoundError",
    "CapabilityRequirement",
    "Contribution",
    "EffectScope",
    "EventDispatcher",
    "EventStop",
    "FunctionPlugin",
    "KernelError",
    "Plugin",
    "PluginContext",
    "PluginDependencyError",
    "PluginError",
    "PluginHandle",
    "PluginLoadError",
    "PluginManager",
    "PluginRecord",
    "PluginReference",
    "PluginSpec",
    "PluginState",
    "PluginUnloadError",
    "Registration",
    "RegistrationError",
    "Registry",
    "RegistryView",
    "ScopePath",
    "ScopeSegment",
    "discover_entrypoint_plugins",
    "import_plugin",
    "load_yaml_references",
    "plugin",
    "MODEL_PROVIDER_CAPABILITY",
    "AnthropicMessagesMapping",
    "AttemptOutcome",
    "AttemptRecord",
    "AudioContent",
    "BUILTIN_PROVIDER_TEMPLATES",
    "BlockEnd",
    "BlockStart",
    "CancellationToken",
    "CandidateEvaluation",
    "CandidateMetrics",
    "CandidateState",
    "EndpointProbe",
    "ErrorEvent",
    "FinishEvent",
    "FinishReason",
    "HealthStatus",
    "HttpModelProfile",
    "HttpModelProvider",
    "HttpProviderMapping",
    "HttpProviderTransport",
    "HttpRequest",
    "HttpStreamDecoder",
    "HttpStreamFormat",
    "HttpStreamFrame",
    "HttpxOpenAICompatibleTransport",
    "HttpxProviderTransport",
    "ImageContent",
    "InvocationPolicy",
    "InvocationPolicyProtocol",
    "MessageRole",
    "ModelCapability",
    "ModelDescriptor",
    "ModelError",
    "ModelExecutor",
    "ModelFailure",
    "ModelFailureKind",
    "ModelMessage",
    "ModelInvocationError",
    "ModelInvocationResult",
    "ModelProvider",
    "ModelProviderProbe",
    "ModelRegistry",
    "ModelRequest",
    "ModelResponse",
    "ModelRouter",
    "ModelStreamProtocolError",
    "GeminiGenerateContentMapping",
    "OllamaChatMapping",
    "OpenAICompatibleModelProfile",
    "OpenAICompatibleProvider",
    "OpenAICompatibleTransport",
    "PeriodicProbeService",
    "ProbeCache",
    "ProbeCheck",
    "ProbeLevel",
    "ProbeMode",
    "ProbeResult",
    "ProbeStatus",
    "ProviderTemplate",
    "ProviderTemplateRegistry",
    "QwenDashScopeMapping",
    "RouteCandidate",
    "RouteDecision",
    "RouteRequest",
    "RoutingError",
    "RoutingPolicy",
    "RoutingWeights",
    "TextContent",
    "TextDelta",
    "TokenUsage",
    "ToolCallContent",
    "ToolCallDelta",
    "ToolDefinition",
    "ToolResultContent",
    "UsageEvent",
    "WeightedRoutingPolicy",
    "YamlRoutingPolicy",
    "anthropic_provider",
    "builtin_provider_template_registry",
    "collect_stream",
    "deepseek_provider",
    "gemini_provider",
    "glm_provider",
    "ollama_provider",
    "qwen_compatible_provider",
    "qwen_native_provider",
    "turbo_provider",
]
